version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    labels:
      - "dependencies"
    versioning-strategy: increase
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-config-*"
          - "eslint-plugin-*"
      prettier:
        patterns:
          - "prettier"
          - "eslint-config-prettier"
          - "eslint-plugin-prettier"
